package ChatApp;


/**
* ChatApp/Chat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Monday, 7 June, 2021 10:57:25 PM IST
*/

public interface Chat extends ChatOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Chat
